use std::path::PathBuf;

use iced::Point;

use crate::state::{ColorIdx, ColorValue, PixelCoord, TileCoord, TileIdx};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SelectionSource {
    MainArea,
    Tileset,
}

#[derive(Debug, Clone)]
pub enum Message {
    Event(iced::Event),
    WindowClose(iced::window::Id),
    SaveProject,
    OpenProject,
    ProjectOpened(Option<PathBuf>),
    SettingsDialogue,
    SetPixelSize(f32),
    CloseDialogue,
    ImportDialogue,
    ImportConfirm(Option<PathBuf>),
    ImportROM,
    SelectPalette(String),
    AddPaletteDialogue,
    SetAddPaletteName(String),
    SetAddPaletteID(u8),
    AddPalette,
    DeletePaletteDialogue,
    DeletePalette,
    RenamePaletteDialogue,
    SetRenamePaletteName(String),
    RenamePalette,
    HideModal,
    ClickColor(ColorIdx),
    ChangeRed(ColorValue),
    ChangeGreen(ColorValue),
    ChangeBlue(ColorValue),
    AddTileRow,
    DeleteTileRow,
    // ClickTile(TileIdx),
    TilesetBrush(Point<TileCoord>),
    ClickPixel(PixelCoord, PixelCoord),
    SelectArea(String),
    AddAreaDialogue,
    SetAddAreaName(String),
    SetAddAreaSizeX(u8),
    SetAddAreaSizeY(u8),
    AddArea,
    RenameAreaDialogue,
    SetRenameAreaName(String),
    RenameArea,
    DeleteAreaDialogue,
    DeleteArea,
    SelectTheme(String),
    AddThemeDialogue,
    SetAddThemeName(String),
    AddTheme,
    RenameThemeDialogue,
    SetRenameThemeName(String),
    RenameTheme,
    DeleteThemeDialogue,
    DeleteTheme,
    StartTileSelection(Point<TileCoord>, SelectionSource),
    ProgressTileSelection(Point<TileCoord>),
    EndTileSelection(Point<TileCoord>),
    AreaBrush(Point<TileCoord>),
}
