use std::path::PathBuf;

use iced::Point;

use crate::state::{CollisionType, ColorIdx, ColorValue, Flip, Focus, PaletteId, PixelCoord, TileCoord, TileIdx};

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum SelectionSource {
    MainArea,
    Tileset,
}

#[derive(Debug, Clone)]
pub enum Message {
    Event(iced::Event),
    Focus(Focus),
    WindowClose(iced::window::Id),
    SaveProject,
    OpenProject,
    ProjectOpened(Option<PathBuf>),
    SettingsDialogue,
    SetPixelSize(f32),
    CloseDialogue,
    ImportDialogue,
    ImportConfirm(Option<PathBuf>),
    ImportROMProgress,
    ImportROM,
    SelectPalette(String),
    AddPaletteDialogue,
    SetAddPaletteName(String),
    SetAddPaletteID(PaletteId),
    AddPalette,
    DeletePaletteDialogue,
    DeletePalette,
    RenamePaletteDialogue,
    SetRenamePaletteName(String),
    RenamePalette,
    HideModal,
    ClickColor(ColorIdx),
    ChangeRed(ColorValue),
    ChangeGreen(ColorValue),
    ChangeBlue(ColorValue),
    AddTileRow,
    DeleteTileRow,
    // ClickTile(TileIdx),
    SetTilePriority {
        palette_id: PaletteId,
        tile_idx: TileIdx,
        priority: bool,
    },
    SetTileCollision {
        palette_id: PaletteId,
        tile_idx: TileIdx,
        collision: CollisionType,
    },
    TilesetBrush(Point<TileCoord>),
    SelectPixel(PixelCoord, PixelCoord),
    BrushPixel(PixelCoord, PixelCoord),
    SelectArea(String),
    AddAreaDialogue,
    SetAddAreaName(String),
    SetAddAreaSizeX(u8),
    SetAddAreaSizeY(u8),
    AddArea,
    EditAreaDialogue,
    SetEditAreaName(String),
    EditArea,
    EditAreaBGRed(ColorValue),
    EditAreaBGGreen(ColorValue),
    EditAreaBGBlue(ColorValue),
    DeleteAreaDialogue,
    DeleteArea,
    SelectTheme(String),
    AddThemeDialogue,
    SetAddThemeName(String),
    AddTheme,
    RenameThemeDialogue,
    SetRenameThemeName(String),
    RenameTheme,
    DeleteThemeDialogue,
    DeleteTheme,
    StartTileSelection(Point<TileCoord>, SelectionSource),
    ProgressTileSelection(Point<TileCoord>),
    EndTileSelection(Point<TileCoord>),
    AreaBrush(Point<TileCoord>),
    OpenTile {
        palette_id: PaletteId,
        tile_idx: TileIdx,
    },
}
