name: Build release

on:
  push:
    tags: [ v* ]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  verify-code:
    name: verify code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      - run: rustup target add x86_64-pc-windows-gnu
      - run: cargo build --release --target x86_64-pc-windows-gnu
